---
name: build and release mtui

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: set up go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false

      - name: show go version
        run: go version

      - name: host build
        run: bash build.sh --build

      - name: cross build (linux/darwin/win)
        run: |
          bash build.sh --macos
          bash build.sh --linux
          bash build.sh --win
