---
name: deploy mtui to github release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-binary:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false

      - name: build mtui for all platforms
        run: |
          bash build.sh --macos
          bash build.sh --linux
          bash build.sh --win

      - name: check dist folder
        run: ls -lh dist/

      - name: deploy binaries to github release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/mtui-darwin-arm64
            dist/mtui-linux-amd64
            dist/mtui-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
